version: "3.7"

services:
  app:
    image: as:latest
    ports:
      - 8080:8080
    environment:
      'spring.data.mongodb.host': mymongo

  mymongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: